# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
# if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  # source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
# fi

eval "$(starship init zsh)"

export DOTFILES=$HOME/dotfiles
export ZSH=$DOTFILES/arch/zsh
export TERM=xterm-256color

echo "\e[1;4;33m\x0aLoading shell configuration\e[0m\n"

### Antigen Configuration
source <(antibody init)
antibody bundle < $ZSH/bundle.txt
echo "\e[32mAntibody \u2714\e[0m"

for file in $ZSH/*.zsh
do
  source "$file"
done

### OPAM
. $HOME/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true

### ls fix
eval `dircolors $HOME/.dircolors`
echo "\e[32mFixed\e[0m \e[33mls colors\e[0m \e[32m\u2714\e[0m"

[ -f ~/dotfiles/zsh/fzf.zsh ] && source ~/dotfiles/zsh/fzf.zsh

# bun completions
[ -s "/home/achrome/.bun/_bun" ] && source "/home/achrome/.bun/_bun"

# bun
export BUN_INSTALL="/home/achrome/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

eval "$($HOME/.cargo/bin/rtx activate zsh)"
rtx use --global node
rtx use --global python

eval "$(zoxide init zsh)"
