eval "$(starship init zsh)"

export DOTFILES=$HOME/dotfiles
export ZSH=$DOTFILES/arch/zsh
export TERM=xterm-256color

echo "\e[1;4;33m\x0aLoading shell configuration\e[0m\n"

### Antigen Configuration
source <(antibody init)
antibody bundle < $ZSH/bundle.txt
echo "\e[32mAntibody \u2714\e[0m"

for file in $ZSH/*.zsh
do
  source "$file"
done

### OPAM
. $HOME/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true

### ls fix
eval `dircolors $HOME/.dircolors`
echo "\e[32mFixed\e[0m \e[33mls colors\e[0m \e[32m\u2714\e[0m"

source <(fzf --zsh)

# bun completions
[ -s "/home/achrome/.bun/_bun" ] && source "/home/achrome/.bun/_bun"

# bun
export BUN_INSTALL="/home/achrome/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

# Gloud cli
[ -s "/opt/google-cloud-cli/completion.zsh.inc" ] && source "/opt/google-cloud-cli/completion.zsh.inc"
[ -s "/opt/google-cloud-cli/path.zsh.inc" ] && source "/opt/google-cloud-cli/path.zsh.inc"

eval "$(~/.local/bin/mise activate zsh)"
mise use --global node
mise use --global python
mise use --global go

eval "$(zoxide init zsh)"
